version: '3.8'

services:
  app:
    build: .
    container_name: auth-api
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/nest-auth-db
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_refresh_secret
      - STRIPE_SECRET_KEY=your_stripe_secret_key
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
